### ISSUE TITLE
uploadFile.php should validate access to the file

### ISSUE THREAD

**Issue by danmarsden** [Tomax-Think-Academy/moodle-plagiarism_tomagrade#14]
It looks like the file accepts any filehash and doesn't check to see if the file is associated with the coursemodule, or if theuserid matches the value it's expecting.

Please don't allow users to pass any filehash they want to this file - please ensure that the logged in user can actually view the file they are working with.

**Comment by guysiTomax** [comment]
@danmarsden the comment is not clear, the uploadFile.php is used to upload an assignment from Moodle to TomaGrade, the Moodle user don't provide file hash or even the file,
this is an action call from a button on the  lecturer assignment submission view  for which he can choose to upload to TomaGrade the submitted assignment.

**Comment by danmarsden** [comment]
see:
https://github.com/Tomax-Think-Academy/moodle-plagiarism_tomagrade/blob/main/uploadFile.php#L52

you accept "hash" from the end user as a parameter in the url (using $_GET which is also a bug referred to elsewhere)
which you then pass directly into a get_file_by_hash function here:
https://github.com/Tomax-Think-Academy/moodle-plagiarism_tomagrade/blob/main/uploadFile.php#L55

this means that the end user could pass any hash they want to in this url gaining access to any file they know the contenthash for - even if they should not be able to access the file. 

you need to check if this user, is allowed to access the content hash being passed - it should not allow access to any file on disk. - you could do that in a few different ways - ideally you would be checking the component/context/file area to see if this user is allowed to access this file but you will need to improve a few things in your code to do this and unfortunately I'm not really in a position to write this code for you, so if you are stuck you could post a question in the moodle.org forums, or contact a moodle partner to help you tidy up the code.

hope that helps!

**Comment by guysiTomax** [comment]
fixed on branch Moodle_fixes, commit 001bf9961552e75a5f050ccbf72496c5abb1a712

**Comment by guysiTomax** [comment]
merged
