### ISSUE TITLE
code in upgrade.php not wrapped in version checks

### ISSUE THREAD

**Issue by danmarsden** [Tomax-Think-Academy/moodle-plagiarism_tomagrade#6]
https://github.com/Tomax-Think-Academy/moodle-plagiarism_tomagrade/blob/main/db/upgrade.php#L114-L115

these shouldn't be here - it's better to set default values in your settings.php file and docs that cover how to set it up.

**Comment by guysiTomax** [comment]
fixed in commit d928ac55e7a010e2f2c186da2ce0f05eb8ce693d
