### ISSUE TITLE
Defined MOODLE_INTERNAL checks when config.php included in in-line files

### ISSUE THREAD

**Issue by danmarsden** [Tomax-Think-Academy/moodle-plagiarism_tomagrade#7]
when you include the moodle config.php file, you don't need to use the MOODLE_INTERNAL  check - you only need to do that for files that are classes/lib files and not in-line php files that already include config.php

more info here:
https://docs.moodle.org/dev/Coding_style#Require_.2F_include

**Comment by guysiTomax** [comment]
Fixed in commit https://github.com/Tomax-Think-Academy/moodle-plagiarism_tomagrade/commit/e24cabdff424cdfdcdd7f4085ede0cb00193c822
