### ISSUE TITLE
Missing capability checks

### ISSUE THREAD

**Issue by danmarsden** [Tomax-Think-Academy/moodle-plagiarism_tomagrade#8]
Files like clearlogs should have capability check in place - should this logged in user be able to trigger this action - I don't think any user logged in should be able to delete logs.

Please check all files to ensure appropriate capability checks are in place.

for more info see:
https://docs.moodle.org/dev/Security#Verify_course_and_module_access

**Comment by danmarsden** [comment]
resetexam.php looks pretty worrying too - any logged in user can trigger a reset of the grades of any tomax activity.

**Comment by guysiTomax** [comment]
clearlogs fixed at 45809279dc367db6fa7a9dfffb995dd9fa1d08e5
resetexam fixed at c7494003c3a38bd064bb01a185a275caa4082127

**Comment by guysiTomax** [comment]
merged
