### ISSUE TITLE
Direct access to raw $_GET/$_POST/$_REQUEST is not allowed

### ISSUE THREAD

**Issue by danmarsden** [Tomax-Think-Academy/moodle-plagiarism_tomagrade#9]
Raw access to these variables is not allowed - please use our optional/required_param functions with appropriate cleaning.

more info in here:
https://docs.moodle.org/dev/Security#Don.27t_trust_any_input_from_users

Please note this is a definite blocker for approval.

**Comment by guysiTomax** [comment]
fixed in commits:

- bf5b2c1432b4f7322278d97955ca6c725ef50ceb
- 30ad985263563780d9bbc83e0247c4b339121d00
- 04de03cad8e4fc4b7ab9dda404b0e33d4d789412
- 9d95d2dd9b2cb9df856d527077feefa94bc24e0c
